### ISSUE TITLE
Modeling benchmarks failing

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-benchmarks#75]
@nden - it looks like some of the modeling benchmarks are currently failing:

```
[ 22.46%] ···· Traceback (most recent call last):
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 1039, in main_run_server
                   main_run(run_args)
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 913, in main_run
                   result = benchmark.do_run()
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 412, in do_run
                   return self.run(*self._current_params)
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 506, in run
                   min_run_count=self.min_run_count)
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/asv/benchmark.py", line 569, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/home/travis/miniconda/envs/test/lib/python3.6/timeit.py", line 178, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/home/travis/build/astropy/astropy-benchmarks/benchmarks/modeling/compound.py", line 77, in time_large
                   r, d, = self.model(x_no_units_large * u.pix, x_no_units_large * u.pix)
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/core.py", line 386, in __call__
                   __call__, args, [('model_set_axis', None)])
                 File "/home/travis/miniconda/envs/test/l/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/core.py", line 2349, in <lambda>
                   (evaluate(*chain(inputs, islice(params, n_params))),)
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/modeling/functional_models.py", line 479, in evaluate
                   return x + offset
                 File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/astropy/units/quantity.py", line 418, in __array_prepare__
                   .format(function.__name__))
               astropy.units.core.UnitsError: Can only apply 'add' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
```

Would you have any time to look into this? (in case it is a regression in astropy)

**Comment by nden** [comment]
I'll take a look today.

**Comment by astrofrog** [comment]
Thanks!

**Comment by nden** [comment]
@astrofrog I don't see errors from modeling running the benchmarks locally with astropy/master.
Instead I see errors from time.  😕 

```
[ 41.99%] ··· ...antityOpSmallArray.time_quantity_np_sqrt_out             failed
[ 41.99%] ···· Traceback (most recent call last):
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 1169, in <module>
                   main()
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 1162, in main
                   commands[mode](args)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 913, in main_run
                   result = benchmark.do_run()
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 412, in do_run
                   return self.run(*self._current_params)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 506, in run
                   min_run_count=self.min_run_count)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 569, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/timeit.py", line 176, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/Users/dencheva/dev/astropy-benchmarks/benchmarks/units.py", line 135, in time_quantity_np_sqrt_out
                   np.sqrt(self.data, out=self.out)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/astropy/units/quantity.py", line 451, in __array_ufunc__
                   out_array = check_output(out, unit, inputs, function=function)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/astropy/units/quantity_helper/converters.py", line 332, in check_output
                   .format(function.__name__)))
               astropy.units.core.UnitTypeError: Cannot store quantity with dimension resulting from sqrt function in a non-Quantity instance.

[ 42.16%] ··· ...QuantityOpSmallArray.time_quantity_np_square            148±0μs
[ 42.32%] ··· ...tityOpSmallArray.time_quantity_np_square_out             failed
[ 42.32%] ···· Traceback (most recent call last):
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 1169, in <module>
                   main()
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 1162, in main
                   commands[mode](args)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 913, in main_run
                   result = benchmark.do_run()
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 412, in do_run
                   return self.run(*self._current_params)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 506, in run
                   min_run_count=self.min_run_count)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/asv/benchmark.py", line 569, in benchmark_timing
                   timing = timer.timeit(number)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/timeit.py", line 176, in timeit
                   timing = self.inner(it, self.timer)
                 File "<timeit-src>", line 6, in inner
                 File "/Users/dencheva/dev/astropy-benchmarks/benchmarks/units.py", line 126, in time_quantity_np_square_out
                   np.power(self.data, 2, out=self.out)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/astropy/units/quantity.py", line 451, in __array_ufunc__
                   out_array = check_output(out, unit, inputs, function=function)
                 File "/Users/dencheva/anaconda3/envs/ape14/lib/python3.7/site-packages/astropy/units/quantity_helper/converters.py", line 332, in check_output
                   .format(function.__name__)))
               astropy.units.core.UnitTypeError: Cannot store quantity with dimension resulting from power function in a non-Quantity instance.
```

**Comment by astrofrog** [comment]
@nden - ok no problem - I think I misread one of the travis logs (it was for an older stable astropy version). It looks like the error you are getting might be from a slightly out of date astropy dev? In any case Travis for astropy dev here is clean, so I'm going to close this.
