### ISSUE TITLE
Some table memory benchmarks failing

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-benchmarks#87]
I haven't had a chance to investigate yet:

```
[ 19.68%] ··· io_ascii.table.TableSuite.mem_table_init                                                                                                   failed
[ 19.68%] ···· Traceback (most recent call last):
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 729, in run
                   sizeof2 = asizeof.asizeof([obj, obj])
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2708, in asizeof
                   s = _asizer.asizeof(*t)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in asizeof
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in <genexpr>
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 [Previous line repeated 1 more time]
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2050, in _sizer
                   infer=self._infer_)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1711, in _typedef
                   v.set(**_numpy_kwds(obj))
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1269, in set
                   self.reset(**d)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1278, in reset
                   raise ValueError('invalid option: %s=%r' % ('base', base))
               ValueError: invalid option: base=-7880

[ 19.84%] ··· io_ascii.table.TableSuite.mem_table_outputter                                                                                              failed
[ 19.84%] ···· Traceback (most recent call last):
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1184, in main_run_server
                   main_run(run_args)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 1058, in main_run
                   result = benchmark.do_run()
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 537, in do_run
                   return self.run(*self._current_params)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/benchmark.py", line 729, in run
                   sizeof2 = asizeof.asizeof([obj, obj])
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2708, in asizeof
                   s = _asizer.asizeof(*t)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in asizeof
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2137, in <genexpr>
                   return sum(self._sizer(o, 0, 0, None) for o in objs)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2075, in _sizer
                   s += z(o, i, d, None)
                 [Previous line repeated 1 more time]
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 2050, in _sizer
                   infer=self._infer_)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1711, in _typedef
                   v.set(**_numpy_kwds(obj))
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1269, in set
                   self.reset(**d)
                 File "/home/tom/python/dev/lib/python3.7/site-packages/asv/extern/asizeof.py", line 1278, in reset
                   raise ValueError('invalid option: %s=%r' % ('base', base))
               ValueError: invalid option: base=-7880
```

**Comment by pllim** [comment]
Should we use `Table.as_array()` instead? See https://github.com/airspeed-velocity/asv/issues/889#issuecomment-555157884
